@echo off
notepad++ BEFE_debug.py
notepad++ BEFE_ElmDef.py
notepad++ BEFE_Enum.py
notepad++ BEFE_errors.py
notepad++ BEFE_expression_ops.py
notepad++ BEFE_FileWords.py
notepad++ BEFE_functions.py
notepad++ BEFE_MinExp.py
notepad++ BEFE_MinExpDict.py
notepad++ BEFE_MinExpList.py
notepad++ BEFE_Namespace.py
notepad++ BEFE_Parse.py
notepad++ BEFE_ParseMethods.py
notepad++ BEFE_ParseStatements.py
notepad++ BEFE_ParseStatics.py
notepad++ BEFE_ParseTree.py
notepad++ BEFE_Range.py
notepad++ BEFE_Span.py
notepad++ BEFE_Stack.py
notepad++ BEFE_Struct.py
notepad++ BEFE_Tree.py
notepad++ BEFE_VarTerm.py
notepad++ BEFE_Word.py
notepad++ BEFE_WordList.py
notepad++ BNF.py
notepad++ BNF_Rule.py
notepad++ BNF_Rules.py
notepad++ mem.py
notepad++ numberCache.py
notepad++ sportr.py
notepad++ t.py
notepad++ x.py
notepad++ __dict.py