#!/usr/bin/env python
# coding=utf-8
#------------------------------------------------------------------------------
#
# File:  cr2lf - Convert text file from CR lines to LF lines
#
# Usage: cr2lf <file>...
#
# Where: <file> is file(s) to convert
#

import sys
from   sys         import  exit
import os
import os.path      as     path
from   utils.errors import *
from   utils.funcs  import *

def expand(path):

  return os.path.abspath(os.path.expanduser(path))

if __name__ == '__main__':

  print('%s __main__ ...'%repr(__file__))

  files = sys.argv[1:]
  if not files:
    Error("Expected one or more arguments")
    exit(1)

  for file in files:
    file = expand(file)
    if not path.exists(file):
      Error("File %s does not exist"%repr(file))
      continue
    contents = open(file).read()
    lines = contents.split('\r')
    numcr = len(lines)-1
    Notice("File %s has %d CR in it"%(repr(file),len(lines)-1))
    if numcr < 1: 
      Notice("File %s has 0 CRs in it, skipping..."%repr(file))
      continue
    contents = open(file).write(lines.join('\n'))
    Notice("File %s fixed (%d CR%s)"%(repr(file),numcr,'' if numcr == 1 else 's'))

