#!/usr/bin/env python3
#================================================================================
#
# File:  extsync
#
# Usage: Move missing files from USB drive to SD card
#
# Notes: This script only works on Linux (intentionally).
#
#================================================================================

from   utils.walker import walk
import                     os
import                     sys
from   utils.errors import *
import                     colr
from   utils.walker import walk
from   funcs        import preEllipse
import                     time

#
# Globals...
#

debug       = False
verbose     = False
veryverbose = True

#------------------------------------------------------------------------------
#
# Function: color - Use colr.color if stdout is a tty
#

def color(*args,**kwargs):

  if not sys.stdout.isatty():
    return args[0]
  return colr.color(*args,**kwargs)

#------------------------------------------------------------------------------
#
# Function: expand - Expand file/path to full path
#

def expand(path):

  return os.path.abspath(os.path.expanduser(path))

#------------------------------------------------------------------------------
#
# Function: copyOneFile 
#
# Usage:    except = copoyOneFile(srcfile,dstfile,pretend=False,overwrite=False)
#
# Where:    srcfile   - str: Source file path
#           dstfile   - str: Destination file path
#           pretend   - bool: True  = Don't actually do it, just pretend
#                             False = Actually do it
#           overwrite - bool: True  = Overwrite existing file contents
#                             False = Skip if exists 
#

def copyOneFile(srcfile,dstfile,pretend=True,overwrite=True):

  # Make sure source file exists...
  if not os.path.exists(srcfile):
    return Exception("Source file %s doesn't exist"%repr(preEllipse(srcfile,75).strip()))

  #
  # Do it...
  #

  dstdir = os.path.dirname(dstfile)
  if not os.path.exists(dstdir):
    os.makedirs(dstdir)

  print('  '+preEllipse(dstfile,75)+'...',end='')

  if os.path.exists(dstfile) and not overwrite:
    print("Exists already, skipping")
    return

  sfd = os.open(srcfile,os.O_RDONLY)
  sstat = os.fstat(sfd)
  filesize = sstat.st_size
  if not pretend:
    dfd = os.open(dstfile,os.O_RDWR|os.O_CREAT)
    #dfd = open(dstfile,'wb')

  prevpercent = -1
  blocksize = 1024*1024 # 1mB at a time
  offset = 0
  while offset < filesize:
    percent = int(float(offset)/filesize * 1000)/10.0
    fstr = '%2.1f%%'%percent
    if len(fstr) < 5: fstr = ' '+fstr
    if percent != prevpercent:
      print('%s\b\b\b\b\b'%fstr,end='')
      sys.stdout.flush()
    prevpercent = percent
    if not pretend:
      os.sendfile(dfd,sfd,offset,blocksize)
    else:
      time.sleep(.01)
    offset += blocksize

  print("Finished")
  
  if not pretend:
    os.close(dfd)
    if overwrite:
      os.truncate(dstfile,filesize)
  os.close(sfd)

  return

#---
#
# Main
#

if __name__ == '__main__':

  srcdir  = expand('~/SRC/bb/_Other/')
  dstdir  = expand('~/DST/bb/_Other/')
  if srcdir[-1] != '/': srcdir += '/'
  if dstdir[-1] != '/': dstdir += '/'
  print('srcdir = %s'%srcdir)
  print('dstdir = %s'%dstdir)
  print('')
  print('Files...')

  files = walk(srcdir)
  for file in files:
    sfile = file
    dfile = dstdir+os.path.basename(file)
    result = copyOneFile(sfile,dfile,pretend=False,overwrite=False)
  print("\nThat's it!")

  sys.exit()
  # ...TEMP

  result = copyOneFile(srcfile,dstfile,pretend=False)
  #result = copyOneFile('/home/bferris57/befe/scripts/extsync','/home/bferris57/DST/extsync',pretend=False)
  if result:
    print(color("ERROR: "+str(result),fore='red',style='bright'))

