#!/usr/bin/env python3

from   utils.funcs import myIps
from   utils.funcs import dtToNonce
from   utils.funcs import dtNow

import                    time
import                    curses
from   curses      import wrapper

def now():

  nonce = dtToNonce(dtNow())
  s     = nonce.split('T')[1][:-4]
  hour  = int(s[:2])
  if hour > 12:
    s = '%02d'%(hour-12) + s[2:] + 'pm'
  else:
    s += 'am'
  return s

def main(stdscr):

  stdscr.clear()
  stdscr.refresh()
  stdscr.timeout(200)
  curses.curs_set(0)

  y = 1
  maxy,maxx = stdscr.getmaxyx()
  stdscr.addstr(y,0,'lines = '+str(maxy))
  y += 1
  stdscr.addstr(y,0,'cols  = '+str(maxx))
  y += 2
  stdscr.addstr(y,0,'Press any \'q\' or \'x\' to exit...')
  stdscr.refresh()
  key = ''
  while key not in ('q','Q','x','X'):
    dt = now()
    stdscr.addstr(0,maxx-len(dt),dt)
    key = stdscr.getch()
    if key < 0: continue
    key = chr(key)

if __name__ == '__main__':

  #print('myIps(): '+repr(myIps()))
  #print('now: '+repr(now()))
  #time.sleep(3)

  wrapper(main)

