#!/usr/bin/env python3

from utils.funcs import *
import                  time
import                  curses
from   curses    import wrapper

def main(stdscr):

  stdscr.clear()
  stdscr.refresh()

  for i in range(0,10):
    v = i-10
    stdscr.addstr(i,0,'10 divided by {} is {}'.format(v,10/v))
    stdscr.refresh()
    time.sleep(1.0)

  stdscr.refresh()
  stdscr.getkey()

if __name__ == '__main__':

  print('myIps(): '+repr(myIps()))

  time.sleep(3)

  wrapper(main)

