#!/usr/bin/env python3

import                    time
import                    curses
from   curses      import wrapper

lines = '∙√─│┌┐└┘├┬┴┼═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬▲►▼◄◊☺☻'

ld_tl   = '┌'
ld_rt   = '┐'
ld_bl   = '└'
ld_br   = '┘'
ld_hor  = '─'
ld_vert = '│'

scr = None

topnum = '┌─x─┐'
top    = '┌───┐'
mid    = '│   │'
midnum = '│ x │'
bot    = '└───┘'

visChar = ' A23456789TJQK'

def renderDealt(y,x,deck):

  if not deck:
    return

  for i in range(0,len(deck)-1):
    card = deck[i]
    if card < 0:
      tstr = top
    else:
      tstr = visChar[card].join(topnum.split('x'))
    scr.addstr(y+i,x,tstr)
  
  card = deck[-1]
  y = y + len(deck) - 1
  scr.addstr(y  , x, top)
  scr.addstr(y+1, x, mid)
  scr.addstr(y+2, x, visChar[card].join(midnum.split('x')))
  scr.addstr(y+3, x, mid)
  scr.addstr(y+4, x, bot)
  scr.refresh()
      
def main(screen):

  global scr

  scr = screen

  scr.clear()
  scr.refresh()
  scr.timeout(200)
  curses.curs_set(0)

  y = 1
  maxy,maxx = scr.getmaxyx()
  scr.addstr(y,0,'lines = '+str(maxy))
  y += 1
  scr.addstr(y,0,'cols  = '+str(maxx))
  y += 2
  scr.addstr(y,0,'Press any \'q\' or \'x\' to exit...')
  y += 2
  scr.refresh()

  deck = [-1,-1,-1, 2, 5, 13, 10, 1]
  renderDealt(y,0,deck)

  key = ''
  while key not in ('q','Q','x','X'):
    dt = 'Dude!'
    scr.addstr(0,maxx-len(dt),dt)
    key = scr.getch()
    if key < 0: continue
    key = chr(key)

if __name__ == '__main__':

  wrapper(main)

