#!/usr/bin/env python
#coding=utf-8

from time        import sleep
from sys         import stdout
import                  sys
import                  os
#from utils.funcs import *
from utils.walker import walk

if False:
  i = 1
  print('Number:   0%',end='')
  for i in range(1,101):
    print('\b\b\b\b%3d%%'%i,end='')
    stdout.flush()
    sleep(.2)
  print('')

if False:

  x = "abcdefghijklmnopqrstuvwxyz"
  y = postellipse(x,10)

if False:

  print('sys.path = '+repr(sys.path))
  for key in os.environ:
    print('%s = %s'%(key,os.environ[key]))

if True:

  dirs = walk('.',dirsonly=True)
  print("dirs = %s"%repr(dirs))
