#!/usr/bin/env python
#coding=utf-8

from time import sleep
from sys  import stdout
import           sys
import           os

if False:
  i = 1
  print('Number:   0%',end='')
  for i in range(1,101):
    print('\b\b\b\b%3d%%'%i,end='')
    stdout.flush()
    sleep(.2)
  print('')

if True:

  x = os.path.join('abc','def')
  print(x)
