.PHONY: clean All

All:
	@echo "----------Building project:[ BEFE_Dev - Debug ]----------"
	@cd "BEFE_Dev" && $(MAKE) -f  "BEFE_Dev.mk"
clean:
	@echo "----------Cleaning project:[ BEFE_Dev - Debug ]----------"
	@cd "BEFE_Dev" && $(MAKE) -f  "BEFE_Dev.mk" clean
